//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ph_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhContext : DbContext
    {
        public PhContext()
            : base("name=PhContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cluster> ClusterSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Corporation> CorporationSet { get; set; }
        public virtual DbSet<Class> ClassSet { get; set; }
        public virtual DbSet<Skill> SkillSet { get; set; }
        public virtual DbSet<Feature> FeatureSet { get; set; }
        public virtual DbSet<CelestialBody> CelestialBodySet { get; set; }
        public virtual DbSet<SkillAssignment> SkillAssignmentSet { get; set; }
        public virtual DbSet<FeatureAssignment> FeatureAssignmentSet { get; set; }
        public virtual DbSet<Fleet> FleetSet { get; set; }
        public virtual DbSet<Ship> ShipSet { get; set; }
        public virtual DbSet<Station> StationSet { get; set; }
        public virtual DbSet<ShipType> ShipTypeSet { get; set; }
        public virtual DbSet<StationModule> StationModuleSet { get; set; }
        public virtual DbSet<StationModuleAssignment> StationModuleAssignmentSet { get; set; }
        public virtual DbSet<StationType> StationTypeSet { get; set; }
        public virtual DbSet<JobStatusInfo> JobStatusInfoSet { get; set; }
    }
}
