//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ph_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureAssignment
    {
        public int Id { get; set; }
        public int FeatureId { get; set; }
        public int CorporationId { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Corporation Corporation { get; set; }
    }
}
