//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ph_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public Level Level { get; set; }
        public string MemberName { get; set; }
        public int LineNumber { get; set; }
        public string Message { get; set; }
    }
}
