//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ph_model
{
    using System;
    
    public enum PlanetType : int
    {
        Terra = 0,
        Gas = 1,
        Ice = 2,
        Lava = 3
    }
}
