//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ph_model
{
    using System;
    
    public enum StarType : int
    {
        Typeg = 0,
        Supernova = 1,
        Dualstar = 2,
        Redgiant = 3,
        Reddwarf = 4,
        Whitedwarf = 5
    }
}
